# Generated by Django 4.2.9 on 2024-03-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='pic',
            field=models.ImageField(default='no_picture.webp', upload_to='ingredients'),
        ),
    ]
